// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/zh_CN/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/content-scripts/floating-chat.js"
    | "/content-scripts/main-world.js"
    | "/deepseek/sha3_wasm_bg.wasm"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/logo.png"
    | "/pet/deepseek-whale-pet-states.png"
    | "/sandbox-offscreen.html"
    | "/sandbox-runner.html"
    | "/sidepanel.html"
    | "/wxt.svg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
